print("Please enter a character for Boops eye")
eye = input()
print('      \_/')
print(f'     ({eye} {eye})')
print('    __)#(__')
print('   ( )...( )(_)')
print('   || |_| ||//')
print('>==() | | ()/')
print('   _(___)_)')
print('   [-]   [-]')