print('Please enter the number of lives.')
lives=int(input())
print(' Please enter the energy level.')
energy=int(input())
print('Please enter the shield level.')
shield=int(input())

print(f'Lives:  {"♥"*lives}')
print(f'Energy: ♦{*lives}')
print(f'Shield: ♦{*lives}')